# This is the default format.
# For more see: https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:categories/:year/:month/:day/:title

exclude: ["LICENSE"]
highlighter: rouge

# Themes are encouraged to use these universal variables
# so be sure to set them if your theme uses them.
title : Fondamenti-II
author :
  name : Federico Bolelli, PhD 
  email : federico.bolelli@unimore.it
  github : prittt
  twitter : nill
  feedburner : nill

production_url : https://prittt.github.io

# Tell Github to use the kramdown markdown interpreter
# (see https://help.github.com/articles/migrating-your-pages-site-from-maruku)
markdown: kramdown